[package]
name = "riscvvm"
version = "0.1.0"
authors = ["JO Jaeyoung <jojaeyoung.se@gmail.com>"]
license = "MIT"

[dependencies]
getopts = "0.2.14"
log = "0.3.8"
env_logger = "0.4.3"
num = "0.1.40"
enum_primitive = "*"
rustbox = "*"
backtrace = "0.3"
